# Generated by Django 4.2.1 on 2023-08-16 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionitem'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
