# Generated by Django 4.2.1 on 2023-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionitem_highest_bid_alter_bid_item_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(default='598846.jpg', upload_to='auction_images/'),
        ),
    ]
