# Generated by Django 4.2.1 on 2023-08-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='auction_status',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
