# Generated by Django 4.2.1 on 2023-08-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionitem_auction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='image',
        ),
    ]
